### ISSUE TITLE
Can't mine any of the gems with reasonable pickaxe.

### ISSUE THREAD

**Issue by PixelatedBruh** [kwpugh/MoreGems#1]
iron or diamond pick cannot mine any of the gems in version 1.15.2-1.0.1

**Comment by kwpugh** [comment]
Hmm, I just fired it up and works fine with both iron and diamond pickaxe.

Can you post any other mods you are playing with?

**Comment by kwpugh** [comment]
wait, works in dev, but not in a launcher, need to look further

**Comment by kwpugh** [comment]
Found the problem.

Just posted v1.0.2 which fixes it.
