### ISSUE TITLE
Compat with Tiered mod.

### ISSUE THREAD

**Issue by RDKRACZ** [kwpugh/MoreGems#10]
Can You add support for [Tiered](https://www.curseforge.com/minecraft/mc-mods/tiered) mod? Mod [GitHub](https://github.com/Draylar/tiered).
This mod gives tools, armor, and weapons random qualities when they enter your inventory, inspired by Terraria tools. All the qualities, as well as the tools that can get them, are completely configurable.
![image](https://user-images.githubusercontent.com/43277609/101697272-ce348600-3a77-11eb-9bfa-03d5a2913954.png)

Seems like You would need to do this - "Mods need to add their tools to the respective tags inside the fabric namespace (fabric:pickaxes, fabric:chestplates, fabric:shovels, etc.)" - https://github.com/Draylar/tiered/issues/12

**Comment by kwpugh** [comment]
<img width="496" alt="Screen Shot 2020-12-10 at 10 00 21 AM" src="https://user-images.githubusercontent.com/8809210/101796542-a15f8d80-3ace-11eb-918e-87e0cd59caf7.png">

Already does.

**Comment by RDKRACZ** [comment]
Weird. I checked more items this time and seems like nearly all of them work with Tiered but not all

**Comment by RDKRACZ** [comment]
Emerald Sword, Emerald Shovel, Emerald Axe, Emerald Hoe, Emerald Excavator. It seems like only these don't work

**Comment by kwpugh** [comment]
done in latest.
