### ISSUE TITLE
Ruby pickaxe not mining Carbonado

### ISSUE THREAD

**Issue by Lordbaane** [kwpugh/MoreGems#11]
Made a ruby pickaxe to mine carbonado and it wasn't working.

**Comment by kwpugh** [comment]
I was just testing that in dev and it works.   Please confirm you are using the latest version MoreGems-Fabric_1.16.4-1.1.13.

**Comment by kwpugh** [comment]
also, what version of minecraft are you on?   1.16.4?

**Comment by Lordbaane** [comment]
You know, it might be another mod that has the same image for the ruby that you have. In 1.16.4 More Gems, Vanilla Enhanced, and Emerald tools all have the same image. So it might be a different mod that I am mixing it up with for the pickaxe.

**Comment by kwpugh** [comment]
in game, you can press F3 + G to turn on hidden tooltips.  you can see the mod_item_name under the item description.

**Comment by Lordbaane** [comment]
I'll give it a shot and close it for now. Thanks.
