### ISSUE TITLE
Editing the config makes ores not harvestable 

### ISSUE THREAD

**Issue by PixelatedBruh** [kwpugh/MoreGems#13]
hey it is me again

on version 1.16.5 editing the config for the mod makes the ores not be able to mine with any pickaxe

tested on server and single player with just more gems installed

fabric api 0.29.4

also just as a suggestion to make the bows also be part of the extra tools config.

**Comment by kwpugh** [comment]
It might be a bad character somewhere.  Did you try deleting the config, restart and let it create a new one?

If so, please attach the config.

**Comment by PixelatedBruh** [comment]
Yes I did and it worked fine when it made a new one. But Trippel checked that I only changed true to false and nothing else.

here is the config I edited.

{ 
	/* ********
	   Juju
	   ********
	*/
	"jujuEnable": false,
	"jujuChance": 0.019999999552965164,
	/* ***************
	   Enchantments
	   ***************
	*/
	"enableQuickening": false,
	"enableRazorSharpness": false,
	"enableShulkerBlade": false,
	"enableUntouchable": false,
	"enableFasterObsidian": false,
	"amountHalfHeartsQuickening": 10.0,
	"enemySlownessDurationTicksQuickening": 300,
	"razorDamageIncrease": 6.0,
	"untouchableDamage": 7,
	"shulkerBladeDurationTicks": 300,
	/* ********************************
	   Paxels, Hammers, & Excavators
	   ********************************
	*/
	"extraToolsEnable": false
}

**Comment by kwpugh** [comment]
Just published v1.1.21 that fixes the problem and adds config options.

UPDATES:

Fixed issue of pickaxes not working on ores when extra tools are disabled via config

Added config options to enable/disable bows and the gembag

Let me know if you have any issues.
