### ISSUE TITLE
[1.17] Use newer gradle version.

### ISSUE THREAD

**Issue by RDKRACZ** [kwpugh/MoreGems#14]
In use is v6.3 from Mar 24, 2020, and the newest stable is v6.8.3 from Feb 22, 2021.

**Comment by kwpugh** [comment]
Is there a problem?

**Comment by RDKRACZ** [comment]
No it works fine but I just hate when I have so many gradle versions downloaded on my system because every mod uses a different one instead of few last ones.

**Comment by kwpugh** [comment]
I will add it to the list of 1.17 "to-dos"

**Comment by kwpugh** [comment]
Are you working on a fork of the code?

**Comment by RDKRACZ** [comment]
No, I'm even not a coder but I like to compile various mods to test upcoming features and report broken things.

**Comment by kwpugh** [comment]
Kind of a waste with my mods, I don't push to GitHub until after a published release or whenever I remember to.  My local computer is the master source.  So my GitHub is likely dated code, not current or future.

**Comment by RDKRACZ** [comment]
Gradle 7 was released a few days ago, it brings compatibility with Java 16 (build fails with Gradle 6.*). There is also Loom 0.7, and my pr with Polish translations. Maybe you can reconsider an update before the 1.17 release? Just asking, no pressure.

**Comment by kwpugh** [comment]
Updated to grade 7.0.2
