### ISSUE TITLE
[1.16.5] Conflict with Harvest Scythes mod

### ISSUE THREAD

**Issue by LiviiYS** [kwpugh/MoreGems#19]
Game crashes when i use this mod with harvest scythes 

Crash log: https://zerobin.net/?0c4aa7167d8ddd48#Wk5T8gN7u4T8+pswL5WDEIsOcbcGWLbZbTeHTPnOPvM=

**Comment by kwpugh** [comment]
harvest scythes built compatibility for my materials.  I recently changed the structure of my material to allow for greater customization via config.  harvest scythes is trying to load a class that no longer exists, that is why it is crashing.  You will not be able to use the mods together until harvest scythes updates the support for MoreGems.

**Comment by kwpugh** [comment]
Looks like the latest release of Harvest Scythes fixes the issue.
