### ISSUE TITLE
shaped vs shapeless recipes [Bug? Enhancement?]

### ISSUE THREAD

**Issue by Linguardium** [kwpugh/MoreGems#2]
not necessarily a bug, but i noticed you use shaped recipes rather than shapeless  for block gem conversion, which means that you _must_ put blocks in the very center of the crafting table to convert them. 

A shapeless recipe would allow a block in any slot (or even in the 2x2) instead.

i checked the _block_to_gem.json files and the ones i saw had this "issue"

**Comment by kwpugh** [comment]
I will update that

**Comment by kwpugh** [comment]
Fixed in next update
