### ISSUE TITLE
[No issue] Required dependency is not marked as required.

### ISSUE THREAD

**Issue by RDKRACZ** [kwpugh/MoreGems#21]
Judging by the jars section in the fabric.mod.json file mods Auto Config Updated API and PlayerAbilityLib are required but they aren't mentioned in the depends section.
```
  "depends": {
    "fabricloader": "\u003e\u003d0.7.4",
    "fabric": "*",
    "minecraft": "1.16.x"
  },
  "suggests": {
    "flamingo": "*"
  },
  "jars": [
    {
      "file": "META-INF/jars/autoconfig1u-3.2.2.jar"
    },
    {
      "file": "META-INF/jars/PlayerAbilityLib-1.2.1.jar"
    }
  ]
```

Also, the `suggests` could be removed.

**Comment by kwpugh** [comment]
All of this is required.   The jars are compiled in the dev environment and not needed to be added by the user.

Unless something functional is broken, please do not open issues just because you do not understand or do not like my code.

Thank you.
