### ISSUE TITLE
[1.17] JuJus when in trinket slots lose their effects

### ISSUE THREAD

**Issue by CrisInuyasha** [kwpugh/MoreGems#23]
It seems JuJus when equipped in the necklace slot lose their effects. Tried with Amethyst JuJu and Emerald JuJu

**Comment by kwpugh** [comment]
Does not support Trinkets.

**Comment by kwpugh** [comment]
Not sure if I will add Trinkets.  I dislike the layout and don't like that it requires hard coding that makes it a required dependency.   I'm hoping for a better alternative to emerge at some point.   Curios API was, in my opinion, a better choice, but it is not moving to 1.17.  I have heard that there is a fork of Curios underway, so I plan to wait and see.
