### ISSUE TITLE
[1.16.5] Crash on startup

### ISSUE THREAD

**Issue by esotericdesign** [kwpugh/MoreGems#24]
Hello.
For some reason, Minecraft crashes immediately. Logs show the 'initializing game' exception and blame More Gems specifically. I used latest mod version, then updated Fabric loader and Fabric API, nothing worked. Nor did downgrading to latest-but-one version. Is there a dependency missing?
Here's one of the logs.
[moregems.txt](https://github.com/kwpugh/MoreGems/files/6771421/moregems.txt)

**Comment by kwpugh** [comment]
In the log it. is looking for Curios API, which is a dependency

**Comment by kwpugh** [comment]
Add Curios API and try again.

**Comment by esotericdesign** [comment]
That did the trick! Thanks a lot!

**Comment by kwpugh** [comment]
Enjoy.
