### ISSUE TITLE
Can't Eat

### ISSUE THREAD

**Issue by Inkquill256** [kwpugh/MoreGems#25]
When I use the latest version of More Gems, I can't eat. Do you know what might be causing it?

Loader Version: 1.17.1-11.6
More Gems Version: 1.17.1-1.2.24
Mod List: 

![Screenshot 2021-07-16 174014](https://user-images.githubusercontent.com/83196535/126015111-c1d59d87-c658-4103-b928-c374306ef6b9.jpg)
![Screenshot 2021-07-16 174105](https://user-images.githubusercontent.com/83196535/126015134-49f4933d-d745-4363-aff6-aead10b88ba9.jpg)
![Screenshot 2021-07-16 174142](https://user-images.githubusercontent.com/83196535/126015142-951f9da1-6c3e-473d-b03e-21ba7a3823a3.jpg)
![Screenshot 2021-07-16 174208](https://user-images.githubusercontent.com/83196535/126015150-00f824b7-da6c-4dc9-9f18-adf64c9e48a0.jpg)

**Comment by kwpugh** [comment]
fixed

**Comment by Inkquill256** [comment]
Thank you!
