### ISSUE TITLE
[1.17] Possible excavator break issue on a particular server

### ISSUE THREAD

**Issue by Kxchu** [kwpugh/MoreGems#26]
the excavator doesn't seem to be mining 3x3, it randomly did once but idk what's wrong with it

**Comment by kwpugh** [comment]
Are you using the latest version MoreGems-Fabric-1.17.1-1.2.25.jar
?

**Comment by Kxchu** [comment]
Im playing on 1.17, but all I have to do is relog onto the server with the item in my hand so no worries. Probably a server side issue

**Comment by kwpugh** [comment]
which version of the mod?

**Comment by Kxchu** [comment]
MoreGems-Fabric-1.17.1-1.2.25

**Comment by kwpugh** [comment]
does it happen to you playing in single player?

**Comment by Kxchu** [comment]
nope hast happened in single player yet, but I would appreciate a way to limit the range. as in a way to choose between 1x1 2x2 and 3x3 ect

**Comment by kwpugh** [comment]
if you sneak it does 1x1

**Comment by Kxchu** [comment]
oh I see thank you very much :)

**Comment by kwpugh** [comment]
Is anyone else on the server having the same issue?

**Comment by kwpugh** [comment]
is this still happening with 1.17.1 version?

**Comment by kwpugh** [comment]
Is this still happening with the latest version of the mod for 1.17.1?

**Comment by kwpugh** [comment]
Related report:  https://github.com/kwpugh/MoreGems/issues/28

Need to confirm they are using the latest version.

**Comment by kwpugh** [comment]
no further data, closing.
