### ISSUE TITLE
[1.17.1] [Suggestion] Add Enchantment Descriptions

### ISSUE THREAD

**Issue by kalinzange** [kwpugh/MoreGems#27]
If it's possible to add enchantment description on [Enchantment Descriptions Mod](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)

![image](https://user-images.githubusercontent.com/38161086/127532075-189e205f-d5f9-4075-b8d0-273e67090f94.png)

**Comment by kwpugh** [comment]
No plans for this in the future.  Enchant descriptions are available on the mods curse forge pages.
