### ISSUE TITLE
Excavator Would constantly break and work like a normal shovel 80% of the time

### ISSUE THREAD

**Issue by Kenocrystal** [kwpugh/MoreGems#28]
Version 1.17 - MoreGems-Fabric-1.17-1.2.16

Excavators would break after a few uses and work like a normal shovel and would not break in 3x3, have no idea why this happens, it just does - Its very frustrating

**Comment by kwpugh** [comment]
Use the latest MoreGems-Fabric-1.17.1-1.2.27.jar
, it should not be happening anymore

**Comment by kwpugh** [comment]
Closed to existing open issue.

**Comment by Kenocrystal** [comment]
> Use the latest MoreGems-Fabric-1.17.1-1.2.27.jar
> , it should not be happening anymore

I play in 1.17 for a reason, most of the mods that I use are in 1.17 and are not in 1.17.1 yet

**Comment by kwpugh** [comment]
Have you tried?  Most mods created for 1.17 should run on 1.17.1 without changes.  Either way, I no longer support 1.17.

**Comment by Kenocrystal** [comment]
> Have you tried? Most mods created for 1.17 should run on 1.17.1 without changes. Either way, I no longer support 1.17.

I have, and thats disappointing
