### ISSUE TITLE
[Enhancement] configs for worldgen/tags in recipes

### ISSUE THREAD

**Issue by Linguardium** [kwpugh/MoreGems#3]
Current your gem worldgen is hardcoded (and the recipes dont use tags).

Ideally, you would add your gems/blocks to c:* tags, then use the tags in recipes to allow for unidict style compatibility.

you could then also include configs for selectively disabling gem worldgen to allow for other universal worldgen mods.  This would let modpack developers to not have 4 different types of amethyst block/gems in the world and instead use one.

Just a thought. Keep up the good work.

**Comment by kwpugh** [comment]
Yeah.  I did such things in my Forge mods, but had not learned how things work in Fabric.  The author who ported my VeggieWay mod from Forge used those techniques, so now I have a working example.

**Comment by kwpugh** [comment]
Looking at Tech Reborn, they do c.ruby_gem, another mod does c.ruby.   So is there a standard or is it "Wild West" like Forge?

**Comment by Linguardium** [comment]
There is a discussion on the gem format at the moment but cottonresources is the only real unifying tags at the moment. I would maybe wait on that determination or use the current ruby notation and maybe update when/if they deprecate it

**Comment by Linguardium** [comment]
you could always make your own tag, then add both #c:ruby and #c:ruby_gem to it. this means that if they deprecate one, the other will still provide whats needed from other mods and you can focus on using your own tags
"moregems:ruby" or something

**Comment by kwpugh** [comment]
Does Cotton need to be installed for the c.* tags to work?

**Comment by kwpugh** [comment]
I will be adding the config options in the next update.  I'm going to hold off on the c. tags until a little more clarity comes out.

**Comment by kwpugh** [comment]
I'm doing this for the 1.16 snapshot at this point.  Not sure if I will back port it to the 1.15.2 since 1.16 is getting close to release.

**Comment by kwpugh** [comment]
Both 1.15.2 and the 20W18A snapshot version have been updated:

UPDATES:

Added a config file and options to disable gem ore generation
Adjusted gem block recipes to be shapeless for easier use
Added a config option to disable Juju items
Added config option to disable ore and gem blocks

**Comment by Linguardium** [comment]
and no, tags are not mod dependent. I can add tags to whatever namespace i want, even via a datapack.
i suggested c namespace and naming format since the cotton resource mod is the defacto unidict (and oregen) of fabric

**Comment by kwpugh** [comment]
v32:
- added c:tags for all the gems and updated all recipes to use tags
