### ISSUE TITLE
[1.16.5] Excavators break bedrock

### ISSUE THREAD

**Issue by EleiteRanger** [kwpugh/MoreGems#30]

**Comment by kwpugh** [comment]
what version?

**Comment by EleiteRanger** [comment]
1.16.5 (mod version 1.1.22), don't know if it works on other versions.

**Comment by kwpugh** [comment]
1.1.23 is the latest, to you check that?  I would like to troubleshoot from latest release.

**Comment by EleiteRanger** [comment]
Can't right now, I'm migrating my minecraft account.

**Comment by kwpugh** [comment]
ah.  Also, are you using either my Emerald Tools or Gobber?

**Comment by kwpugh** [comment]
ok, all three share the same embedded tools for hammer, excavator, pixel, etc.  make sure you are using the latest of all three because I updated the embedded tools.   if you have an old and a new, goofy things happen.

**Comment by kwpugh** [comment]
I checked latest, and it does break bedrock, so I will look through that.   I'll see what I can do.

**Comment by kwpugh** [comment]
It is actually a quick fix.  I had logic for the hammer to not break bedrock, but never thought to put it on the excavator.  I will post an update shortly on Curseforge.

**Comment by EleiteRanger** [comment]
Glad to help

**Comment by kwpugh** [comment]
Just pushed a fix with v1.1.24, let me know if you have any other troubles.
