### ISSUE TITLE
Gems Only Mineable With Gem Tools 1.17.1

### ISSUE THREAD

**Issue by ctman48** [kwpugh/MoreGems#31]
Hey, really enjoy your mod! On Fabric I recently switched to 1.17.1 and in this version the only way I can mine the Gems with with Gem tools. I'm not sure if it is another mod causing the issue.
I've attached a list of mods I'm using below:
![mods](https://user-images.githubusercontent.com/88918162/129433531-8732d8ab-910d-4aa3-8511-a5f161f77b40.PNG)

Thank you in advance.

**Comment by kwpugh** [comment]
Hi.  I test each version. with vanilla tools and they. work fine in my tests.   iron pickaxe mines everything except carbonado, which need diamond pickaxe.   You might need to start disabling mods, and testing to see what is causing it.

**Comment by kwpugh** [comment]
Can you post a link to your most recent latest.log so I can see full info?

**Comment by ctman48** [comment]
Thank you for the speedy reply. Here is the Latest Log:
[latest.log](https://github.com/kwpugh/MoreGems/files/6987135/latest.log)

In the mean time I will start disabling some mods to see if it changes anything. I'll post what I find here, then I will close the thread. 

Thanks.

**Comment by ctman48** [comment]
Okay so, I've spent some time disabling mods. I found that Respackopts, LibJF, and Additional Additions were causing the issue of the gems not being mine able. Thanks again for your help.
