### ISSUE TITLE
More Gems [Fabric] Causing Crash

### ISSUE THREAD

**Issue by CodWafer** [kwpugh/MoreGems#34]
When I launch my custom modpack with this mod on version 1.1.22, all goes fine- 
however, since I updated to 1.1.24, it crashes upon starting the game.

Here is the log: https://paste.ee/p/gAQ8z

**Comment by kwpugh** [comment]
Looks like you are missing Curios

**Comment by CodWafer** [comment]
Oh, I never thought to check core mods, as I am used to having them automatically installed when downloading something. Anyways, I added it, and it works. Thanks!
