### ISSUE TITLE
[1.17.1] Enchant incompatibility

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/MoreGems#35]
Shulker Blade seems to be incompatible with Razor Sharpness or even vanilla Sharpness type enchants. Imho this doesn't make sense as I feel Shulker Blade is more of a type of enhanced Knockback and Knockback can be used with Sharpness type enchants.

**Comment by kwpugh** [comment]
Not sure if I  intentionally made  it that  way, I will  take  a look.

**Comment by kwpugh** [comment]
This looks better

<img width="229" alt="Screen Shot 2021-09-14 at 7 10 36 AM" src="https://user-images.githubusercontent.com/8809210/133255206-c60b345a-0457-48a2-8d1a-81e76e4bffa3.png">

**Comment by Muffintiem** [comment]
I forgot to mention it was in 1.18.

**Comment by kwpugh** [comment]
got it.  I already did 1.17.1, doing 1.16.5 now, will do 1.18 after that.

**Comment by kwpugh** [comment]
the 1.18 version is now updated on Curseforge

**Comment by Muffintiem** [comment]
I'm actually having another Enchantment compatibility issue. This time while trying to put Faster Obsidian on my Pixel with Mending, Fortune, Unbreaking, Efficiency.

**Comment by kwpugh** [comment]
yep, efficiency and faster obsidian do go together.

**Comment by Muffintiem** [comment]
That makes sense I guess but it also isn't letting me put it on my other Paxel with just Mending, Unbreaking, and Silk Touch.

**Comment by kwpugh** [comment]
Faster Obsidian is not meant to be combined with anything else.
