### ISSUE TITLE
[1.18] Excavators stop mining 3x3 areas randomly

### ISSUE THREAD

**Issue by Rayxanber** [kwpugh/MoreGems#42]
Gemstone excavators seem to break randomly on our server and stop digging up 3x3 areas. Relogging fixes it but is frustrating to do constantly. Both the Server and the Clients are using version 1.3.29 of the mod (Minecraft 21w44a snapshot). All players have reported the problem.

**Comment by kwpugh** [comment]
Did this start with 1.3.29?

Can I get a system log from the server?

**Comment by Rayxanber** [comment]
Hi

We only just started playing again with this version after several months so I can't say if earlier versions had the problem.

It breaks on (so far as I've seen) grass, dirt, and gravel (vanilla). We haven't got any modded dirt blocks in at this time.

I have the latest log from the server here, from about the last 2 hours. It's happened multiple times in that period so I hope it's helpful.

[2021-11-11-5.log.gz](https://github.com/kwpugh/MoreGems/files/7524672/2021-11-11-5.log.gz)

**Comment by kwpugh** [comment]
Do any of the excavators have enchantments own them?  If so, which enchants?

**Comment by Rayxanber** [comment]
Mine is unenchanted and does it quite often. Another player has Unbreaking and Efficiency on theirs and it does it as well.

**Comment by kwpugh** [comment]
I've been playing for days with MoreGems for days in 21w44a  on my test server, I have not experienced the problem, I'm stumped.  There was nothing inn you log to indicate a problem.

**Comment by kwpugh** [comment]
Only thing a notice, when  the server is lagging, I break a block with excavator and there is a delay until the rest of the blocks around it break.

**Comment by kwpugh** [comment]
What is:  biom4st3r_repackaged_expressions ?

**Comment by Rayxanber** [comment]
I'm sorry :( I wish I knew more about what's going on to help out. The hammers work perfectly, I don't know what the difference is. 

> 
> 
> What is: biom4st3r_repackaged_expressions ?


I believe that must be attached to this mod: https://www.curseforge.com/minecraft/mc-mods/fabric-more-enchantments
that's the author's name

**Comment by kwpugh** [comment]
Yep, I figured that out as well.  I'm looking at thee mixins in that mod.  It does some pretty deep changes into the server side classes that control mining/block breaking and such.  I tried out excavators ton my server with mo'enchants, but I'm not getting the error yet.

**Comment by kwpugh** [comment]
The thing about hammers and excavators is that they shared about 90% of the same code, only different is the part about checking if the surrounding blocks are breakable by aa shovel.

**Comment by Rayxanber** [comment]
So I did a little testing and I cannot for the life of me figure out how to reliably replicate it. It just...happens sometimes. I also check the console and the server is not experiencing any tick lag at the time so I am also stumped. Maybe the problem is somehow just on our end though I don't know how. Sorry for not being more helpful.

**Comment by kwpugh** [comment]
Any more reports of this?

**Comment by Rayxanber** [comment]
I haven't been playing with the mod recently so I can't say for sure, sorry

**Comment by kwpugh** [comment]
Closing, not more reports received and I cannot replicate error.
