### ISSUE TITLE
[1.18.1] Minimal edition

### ISSUE THREAD

**Issue by naciacia** [kwpugh/MoreGems#45]
Please make a lite version containing only the ores and vanilla-like tools from them (or maybe rename this one into "More Gems enhanced"? "More Gems Plus"?

No hammers, Bows, JuJus (which don't make any sense because there are already potions in Minecraft with these effects that are balanced well).
Some of these items are overpowered or/and don't fit your mod (enchantments). Also, the title does not indicate their presence - "More Gems".
Even if we can disable some features, they are still loaded into memory, right?

I think you could move these features into a new mod. You could make it like this - first mod - "More Gems", second mod, an extension to the first (depending on its presence) - "More Gems addon" that would contain all the features cut from the original mod. You can also make the addon embed like your library so that users that don't read the changelog (or the big red part of a description on some other mods. These people...) don't get shocked.

**Comment by kwpugh** [comment]
I'll think about this, but I don't think it is really necessary to split them out since it is a simple matter to disable the extra tools in the config file

![Screen Shot 2021-12-21 at 8 28 51 AM](https://user-images.githubusercontent.com/8809210/146946428-335e5180-30b9-4418-90bb-b459e87573d3.png)
.

**Comment by kwpugh** [comment]
Same with the Juju and the Enchantments:

![Screen Shot 2021-12-21 at 8 31 38 AM](https://user-images.githubusercontent.com/8809210/146946801-a26dcab4-9da8-43f8-aaca-023017566f10.png)
![Screen Shot 2021-12-21 at 8 31 54 AM](https://user-images.githubusercontent.com/8809210/146946802-a98f5619-a454-4c4c-b0d7-822ff11f0acd.png)

**Comment by kwpugh** [comment]
![Screen Shot 2021-12-21 at 8 32 53 AM](https://user-images.githubusercontent.com/8809210/146946926-56336394-0390-4ef5-8a62-cbc3eba38585.png)

**Comment by kwpugh** [comment]
If you want a simple mod with just ores and tools, you might check out:  https://www.curseforge.com/minecraft/mc-mods/gems-and-crystals

It might be more in line with want you are looking for.

**Comment by kwpugh** [comment]
I will not be going forward with splitting out the mod.
