### ISSUE TITLE
[1.18.1] Mining Helper enchantment breaks Fortune.

### ISSUE THREAD

**Issue by Cosmic-Goat** [kwpugh/MoreGems#46]
When a pickaxe is enchanted with both Mining Helper and Fortune, the Fortune enchantment seems to not take effect. You can reproduce this by mining, say, 20 iron ore using a pickaxe wit h Fortune III and Mining Helper, and then using one with just Fortune III. The pickaxe with Mining Helper consistently produces ~1 raw iron per ore, whilst the pickaxe with only Fortune produces the expected ~2 raw iron per ore.

**Comment by kwpugh** [comment]
Under current settings, Fortune cannot work with Mining Helper because the pickaxe isn't breaking the ores, they are broken separately.  I will look into whether this could be different in the future.

**Comment by Cosmic-Goat** [comment]
Ah, okay! I see it calls [world.BreakBlock](https://github.com/kwpugh/MoreGems/blob/1.18.1/src/main/java/com/kwpugh/more_gems/util/MiningHelper.java#L30). Perhaps you could look at how other mods implement this, such as [Vien Mining](https://github.com/TheIllusiveC4/VeinMining/blob/be2f7de2823634a53e774b47a07909e0e685d5dc/fabric/src/main/java/top/theillusivec4/veinmining/veinmining/logic/VeinMiningLogic.java#L214)? I would try this out myself, but unfortunately I don't have a dev environment set up right now. 

Anyways, thank you for the great mod!

**Comment by kwpugh** [comment]
Although it wasn't intentional, I kind of like the trade-off the player has to make between easier mining and getting Fortune.
I don't think I'm going to change this at present.
