### ISSUE TITLE
[1.18.1] Hammer crashes game when hitting shovel diggable/modded ores

### ISSUE THREAD

**Issue by ValynnVisalle** [kwpugh/MoreGems#47]
I was trying to use a hammer (moissanite, if that matters) in creative mode to dig out a large area and when I hit a sand block, it crashed my game. 
I tried it in survival mode and the same thing happened. 
I tested it on sandstone and stone. Both worked perfectly with the 3x3, but when I hit a dirt block, it crashed my game again. 

List of tested blocks that cause a crash:
Sand
Grass block
Dirt
Salt Ore (Foodables Mod)

There could be others that cause this. These are just the ones I have tested myself. I have attached the logs. 
Let me know if you need more info. 

Version: 1.18.1 - 1.3.59.1
Java, Singleplayer World

[crash-2022-03-27_19.30.25-client.txt](https://github.com/kwpugh/MoreGems/files/8359278/crash-2022-03-27_19.30.25-client.txt)
[crash-2022-03-27_19.35.56-client.txt](https://github.com/kwpugh/MoreGems/files/8359279/crash-2022-03-27_19.35.56-client.txt)
[crash-2022-03-27_19.38.23-client.txt](https://github.com/kwpugh/MoreGems/files/8359280/crash-2022-03-27_19.38.23-client.txt)
[crash-2022-03-27_19.40.55-client.txt](https://github.com/kwpugh/MoreGems/files/8359281/crash-2022-03-27_19.40.55-client.txt)
[crash-2022-03-27_19.44.12-client.txt](https://github.com/kwpugh/MoreGems/files/8359283/crash-2022-03-27_19.44.12-client.txt)
[crash-2022-03-27_19.51.03-client.txt](https://github.com/kwpugh/MoreGems/files/8359285/crash-2022-03-27_19.51.03-client.txt)
[crash-2022-03-27_22.30.42-client.txt](https://github.com/kwpugh/MoreGems/files/8359286/crash-2022-03-27_22.30.42-client.txt)
[crash-2022-03-27_22.33.46-client.txt](https://github.com/kwpugh/MoreGems/files/8359287/crash-2022-03-27_22.33.46-client.txt)

**Comment by kwpugh** [comment]
can you try without BetterNether and tell me the result?

**Comment by kwpugh** [comment]
Actually, you have out of date mods of mine.

![Screen Shot 2022-03-27 at 9 57 22 PM](https://user-images.githubusercontent.com/8809210/160319185-8fbabac5-d22c-43cc-808e-adf8e5058227.png)

All of my tool mods use an embedded tool lib, should be at 1.1.18, which fixed the issue.

Emerald Tools
https://www.curseforge.com/minecraft/mc-mods/simple-emerald-tools-fabric/files/3701840

MoreGems
https://www.curseforge.com/minecraft/mc-mods/more-gems-fabric/files/3701839

**Comment by kwpugh** [comment]
The latest fixed the issue with BetterNether

**Comment by ValynnVisalle** [comment]
I have updated the mods. Give me a few minutes to boot them up & try it again.

**Comment by kwpugh** [comment]
Make sure it loads Pugh_tools_1.1.18

**Comment by ValynnVisalle** [comment]
The hammers now work and don't crash the game when hitting a diggable block or modded ore. However, now the excavator is just working like a regular shovel, breaking only 1 block instead of 3x3.

**Comment by kwpugh** [comment]
seems to  be a nagging problem for some people.  I tested that one over and over and I cannot get it to happen with the excavator.

**Comment by kwpugh** [comment]
the excavator should be fixed in the latest version for 1.18.1.
