### ISSUE TITLE
Request to stop deleting files from CurseForge

### ISSUE THREAD

**Issue by spoorn** [kwpugh/MoreGems#48]
Every time you delete a version from CurseForge, it causes modpacks to fail to upload because the file no longer exists.  This happened a few times to me for my modpack  Requesting that you not remove files every time you upload a new version

**Comment by kwpugh** [comment]
I don't generally delete old versions one for one when I upload a new version of the mod, except when the new version is fixing a bug or two that you should update to.  If you are uploading a new version of your modpack, you really should be using the latest version of the mod, not an old one.

**Comment by spoorn** [comment]
I do update the versions, but for modpack stability or other reasons, a modpack author may want to publish using older versions of mod and do a gradual update.  For instance, maybe all I wanted to add was a small utility mod, but if versions are deleted from CF, I now need to update those mods and test

**Comment by kwpugh** [comment]
I see your point.  I'll try to leave a little more space between deletes.

**Comment by Reimirno** [comment]
Is the 19.0 version gone...?
Try to reconstruct a previos 19.0 modpack and this version does not exist anymore on Curseforge; please advise. Thank you :)

**Comment by kwpugh** [comment]
restored:  [MoreGems-Fabric-1.19.0-1.4.20.jar](https://www.curseforge.com/minecraft/mc-mods/more-gems-fabric/files/3841774)

**Comment by Reimirno** [comment]
ty!

**Comment by kwpugh** [comment]
You really out to move on to 1.19.2, quite a few bugs in my mods have been addressed.
