### ISSUE TITLE
[1.19.0] Experience points are not collected when mining ores from MoreGems mod

### ISSUE THREAD

**Issue by lospejos** [kwpugh/MoreGems#49]
Minecraft: `1.19`
Fabric API: `fabric-api-0.55.3+1.19`
MoreGems mod: `MoreGems-Fabric-1.19.0-1.4.18`

When mining more gems mod's ores (f.e. Spinel, Carbonado, tried all of them) using iron PickAxe, **experience green orbs are not displayed and not collected**.

Minecraft: `1.18.2`
Fabric API: `fabric-api-0.55.1+1.18.2`
MoreGems mod: `MoreGems-Fabric-1.18.2-1.3.67`

When mining more gems mod's ores (f.e. Spinel, Carbonado, tried all of them) using iron PickAxe, **experience green orbs are  displayed and collected successfully**.

I'm not sure is it a MoreGems mod problem or not (because I have plenty other mods installed besides this mod), but please check whether it's the MoreGems mode issue.

Thanks.

**Comment by kwpugh** [comment]
Fixed in latest.
